### ISSUE TITLE
running Sensly.py returns null values

### ISSUE THREAD

**Issue by 2Dman** [Altitude-Tech/Sensly#12]
i've followed the manual at instructables: http://www.instructables.com/id/Sensly-Hat-for-the-Raspberry-Pi-Air-Quality-Gas-De/

However, it seems to be missing a thing or two, for one:
Should also clone:
https://github.com/adafruit/Adafruit_Python_GPIO
cd into the directory
sudo python setup.py build
sudo python setup.py install

after that, you can run sensly.py, but it keeps inserting the data into sampledata:
Time, Carbon Monoxide PPM, Ammonia PPM, Carbon Dioxide PPM, Methly PPM, Acetone PPM, Methane PPM, LPG PPM, Hydrogen PPM, Propane PPM, PM10
20:22:46,0,0,0,0,0,0,0,0,0,2227.80952381
20:23:01,0,0,0,0,0,0,0,0,0,2018.60805861
20:23:16,0,0,0,0,0,0,0,0,0,2117.89010989
20:23:31,0,0,0,0,0,0,0,0,0,408.820512821
20:23:46,0,0,0,0,0,0,0,0,0,135.794871795
20:24:00,0,0,0,0,0,0,0,0,0,2007.97069597
20:24:15,0,0,0,0,0,0,0,0,0,2103.70695971
20:24:30,0,0,0,0,0,0,0,0,0,2327.09157509

the null values are normal ? and no temperature or humidity values ?

**Comment by ferazambuja** [comment]
They are "normal" since it looks that the code is broken...

**Comment by phgachoud** [comment]
I close it, as a duplicate issue from #1
