### ISSUE TITLE
No data shown before calibration (Update.sh which is into https://github.com/Altitude-Tech/Sensly_Install project)

### ISSUE THREAD

**Issue by shihlinlu** [Altitude-Tech/Sensly#4]
Followed all instructions as shown on Instructables: http://www.instructables.com/id/Sensly-Hat-for-the-Raspberry-Pi-Air-Quality-Gas-De/.

After the Raspberry Pi restarted and `$ i2cdetect -y 1 `, no data is shown in 05 and 76 positions. 

I have sent several emails to the Altitude Tech team with no response. I believe this might be a faulty sensor issue than with the code.

**Comment by frazerbarnes** [comment]
I have let my colleagues know about the issue. Please email sam@altitude.pw and he should be able to help resolve your problem.

**Comment by Sam-AlteredCarbon** [comment]
Hi shihlinlu, if you could email me directly at sam@altitude.pw I can help you troubleshoot the problem you are having with obtaining data.

**Comment by shihlinlu** [comment]
Thanks for the update. I have sent an email.

**Comment by gitboy122** [comment]
Same issue here altitude guys plz gelp

**Comment by phgachoud** [comment]
@shihlinlu did you solve your problem?? I dont understand your issue description...

**Comment by shihlinlu** [comment]
@phgachoud No, I have not resolved the issue. No data was being calibrated as shown in the instructions link. I received a replacement sensor, but have not had time to test it again. Were you able to calibrate the sensor and collect data?

**Comment by phgachoud** [comment]
the calibration script seems fixed checkout the gpio_calibration_fix branch
and issue comments I let you check it, test it and accept or not my pull
request on master branch

**Comment by gesaleh** [comment]
@phgachoud I pulled your fix it works for the calibration but the data collection still fails with the same error 
```
python Sensly.py
2017-11-14 22:45:43.459 DEBUG Sensly - <module>: start of script
2017-11-14 22:45:43.462 DEBUG Sensly - <module>: debug test this is logged as debug level
 Sensly is warming up please wait for 15 mins

 Heating Completed
Traceback (most recent call last):
  File "Sensly.py", line 306, in <module>
    MQ7Rs_R0 = MQ7.Corrected_RS_RO( MQ7cmd, temperature, humidity, MQ7_t_33H, MQ7_t_85H)
  File "/home/pi/Sensly/Sensors.py", line 104, in Corrected_RS_RO
    correctedrsro = rsroCorrPct * (self.Get_RSR0Ratio(cmd))
  File "/home/pi/Sensly/Sensors.py", line 63, in Get_RSR0Ratio
    self.rsro = float(self.Get_RS(cmd)/self.R0)
  File "/home/pi/Sensly/Sensors.py", line 58, in Get_RS
    self.RS = ((float(self.MaxADC)/float(self.Get_rawdata(cmd))-1)*self.RLOAD)
  File "/home/pi/Sensly/Sensors.py", line 46, in Get_rawdata
    self._device.write_byte(I2C_Addr,cmd)
IOError: [Errno 121] Remote I/O error

```

**Comment by phgachoud** [comment]
@gesaleh for this issue, please see ## my associated branch which is #6 dev/issue6_remote_IO_Error ## I'll try to keep this notation for the future...

1 branch = 1 issue fix

**Comment by phgachoud** [comment]
This issue is moved (closed & copied, [github is unable to move issue](https://stackoverflow.com/questions/9720718/how-do-i-move-an-issue-on-github-to-another-repo)) to the [corresponding project](https://github.com/Altitude-Tech/Sensly_Install/issues/3) because i2cdetect is an installation problem of the HAT, not a problem from gaz detections.
@shihlinlu see other issues to not mix up things... thx
