### ISSUE TITLE
Hat doesn't work

### ISSUE THREAD

**Issue by gesaleh** [Altitude-Tech/Sensly#8]
Hi 
first happy new year
are you giving any support to your hat the woftware on this repository doesn't work at all
thanks to @phgachoud i made same progress where i calibrate but all values are zero except PM
from Altitude team id din't even see one update

can you  please advice if you are existing as company ?

**Comment by MatthewGCampbell** [comment]
Did you try using these files [https://github.com/Altitude-Tech/Sensly/tree/gpio_calibration_fix](url)

**Comment by MatthewGCampbell** [comment]
you might need to type the url into your web browser directly

**Comment by phgachoud** [comment]
@gesaleh I merged the modifications with HEAD. Can you please change your title for this issue that does not describe anything?? Please answer the question of @hughandann50th so that we can close this issue

**Comment by phgachoud** [comment]
Closed because not describing any new issue
